#!/usr/bin/env node
/*
 * Measures every tune in HVSC's Songlengths.md5 with SIDquake's own loop
 * detector, so the results can be compared against HVSC's published lengths.
 *
 * Usage (Windows, from the repo root):
 *   node tools\songlengths\scan.mjs --limit 20            # try 20 songs first
 *   node tools\songlengths\scan.mjs                       # the whole collection
 *   node tools\songlengths\scan.mjs --jobs 12 --engine fp
 *   node tools\songlengths\report.mjs                     # build the outputs
 *
 * Options:
 *   --md5 <file>     Songlengths.md5   (default: <hvsc>/DOCUMENTS/Songlengths.md5)
 *   --hvsc <dir>     folder containing DEMOS/, MUSICIANS/, DOCUMENTS/ ...
 *                    (default: public/HVSC/C64Music)
 *   --out <dir>      where the journal + outputs go (default: tools/songlengths/out)
 *   --jobs <n>       worker threads (default: CPU count - 1)
 *   --engine <name>  fp (libsidplayfp, the default here) or resid (faster, less accurate)
 *   --limit <n>      stop after n songs - use this for a trial run
 *   --shuffle        sample across the whole collection instead of the first n
 *   --redo           ignore the existing journal and start over
 *   --min-loop <s>   shortest repeat counted as a loop (default 2)
 *   --budget-mult <x>  first attempt scans HVSC's length x this, plus 15 s (2.5)
 *   --max-budget <s>   ceiling for any single scan (default 1200)
 *   --only <classes> re-measure entries ALREADY in the journal whose class is in
 *                    this comma-separated list, e.g. --only capped,error
 *   --budget <s>     fixed scan window for a --only pass (default: --max-budget)
 *   --exclude-rsid   drop RSID tunes (kept by default - they render fine)
 *   --include-basic  keep C64-BASIC tunes (excluded by default - they play nothing)
 *
 * USING HVSC'S OWN NUMBERS. Their length tells us roughly how much audio to
 * render: confirming a loop needs a bit over two passes of it, so the first
 * attempt scans 2.5x their figure, capped at --max-budget. It is a HINT, not a
 * ceiling - their list is hand-curated and can be short. There is no retry: a
 * scan that runs out without resolving anything is just reported as capped.
 * Come back later with --only capped --budget 1800 and spend real time on the
 * stragglers.
 *
 * RESUMING. Every result is appended to out/results-<worker>.jsonl the moment it
 * lands, so an interrupted run loses at most whatever was in flight (seconds).
 * Just run the same command again: finished songs are skipped. Nothing is ever
 * rewritten in place, so a kill -9 or a power cut can't corrupt what's there -
 * a torn final line is detected and dropped on the next read.
 *
 * WHY THIS IS A CLI AND NOT A WEB PAGE. ~61k SIDs / ~80k subtunes means hours of
 * compute and tens of thousands of file reads. Node gets direct disk access with
 * no permission prompts, real threads via worker_threads, and can be left running
 * headless. The browser would need the File System Access API, would prompt, and
 * would die with the tab. The sortable HTML table you asked for is generated by
 * report.mjs instead - that part genuinely wants a browser.
 */

import { Worker } from 'worker_threads';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';
import { parseSonglengths } from './parse-md5.mjs';
import { classify, CLASSES } from './classify.mjs';
import { readSidKind, skipReason } from './sid-kind.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..', '..');

const flags = parseArgs(process.argv.slice(2));
const HVSC = path.resolve(flags.hvsc || path.join(REPO, 'public', 'HVSC', 'C64Music'));
const MD5 = path.resolve(flags.md5 || path.join(HVSC, 'DOCUMENTS', 'Songlengths.md5'));
const OUT = path.resolve(flags.out || path.join(HERE, 'out'));
const PUBLIC = path.join(REPO, 'public');
const JOBS = Math.max(1, parseInt(flags.jobs, 10) || Math.max(1, os.cpus().length - 1));
const ENGINE = flags.engine === 'resid' ? 'resid' : 'fp';
const LIMIT = parseInt(flags.limit, 10) || 0;
const MIN_LOOP = Number(flags['min-loop']) || 2;
const BUDGET_MULT = Number(flags['budget-mult']) || 2.5;
const MAX_BUDGET = Number(flags['max-budget']) || 1200;
const SAMPLE_RATE = 44100;
// Recheck mode: instead of measuring what's missing, RE-measure entries already in
// the journal whose class is in this list (e.g. --only capped,error). Pair with
// --budget to give them a fixed, bigger scan window.
const ONLY = typeof flags.only === 'string'
    ? flags.only.split(',').map(s => s.trim()).filter(Boolean) : null;
const FORCE_BUDGET = Number(flags.budget) || 0;
// C64-BASIC tunes are excluded by default: nothing drives the SID, so they measure
// as nothing. Plain RSID tunes are KEPT - measured against libsidplayfp they render
// perfectly well, and dropping them would lose ~3,300 tunes for no gain. The filter
// runs BEFORE --limit, so asking for 100 songs still measures 100 real ones rather
// than 100 candidates of which some are dropped.
const INCLUDE_RSID = !flags['exclude-rsid'];
const INCLUDE_BASIC = !!flags['include-basic'];

for (const [label, p] of [['Songlengths.md5', MD5], ['HVSC folder', HVSC]]) {
    if (!fs.existsSync(p)) {
        console.error(`\nCan't find the ${label}: ${p}`);
        console.error('Pass --md5 <file> and --hvsc <dir> if your copy lives elsewhere.\n');
        process.exit(1);
    }
}
fs.mkdirSync(OUT, { recursive: true });

// ---------------------------------------------------------------------------
// Work list

console.log(`Reading ${MD5}`);
const { entries } = parseSonglengths(fs.readFileSync(MD5, 'utf8'));
console.log(`  ${entries.length.toLocaleString()} entries`);

// One task per SUBTUNE - Songlengths lists one time per subtune, and each is a
// separate piece of music that has to be measured on its own.
let tasks = [];
let missingPath = 0;
for (const e of entries) {
    if (!e.sidPath) { missingPath++; continue; }
    for (let s = 0; s < e.times.length; s++) {
        tasks.push({ md5: e.md5, sidPath: e.sidPath, subtune: s, hvscMs: e.times[s].ms });
    }
}
if (missingPath) console.log(`  ${missingPath} entries had no path comment and were skipped`);
console.log(`  ${tasks.length.toLocaleString()} subtunes listed`);

// Drop the tunes we can't meaningfully measure. Reading 124 header bytes per SID
// is quick but not free across 60k files, so the verdicts are cached beside the
// journal and reused until the source list changes.
const kindCachePath = path.join(OUT, 'sid-kinds.json');
const md5Stat = fs.statSync(MD5);
// The cache holds the header FACTS, not the skip decision - the decision depends on
// the include flags and is recomputed each run, so toggling a flag can't be served a
// stale verdict. report.mjs reads the same file for its Format column.
const kindKey = `${MD5}|${md5Stat.size}|${md5Stat.mtimeMs}|${HVSC}`;
let kinds = null;
try {
    const cached = JSON.parse(fs.readFileSync(kindCachePath, 'utf8'));
    if (cached.key === kindKey) kinds = cached.kinds;
} catch (e) { /* no cache yet */ }
if (!kinds) {
    const paths = [...new Set(tasks.map(t => t.sidPath))];
    process.stdout.write(`  reading ${paths.length.toLocaleString()} SID headers… `);
    kinds = {};
    const CONC = 64;
    for (let i = 0; i < paths.length; i += CONC) {
        const slice = paths.slice(i, i + CONC);
        const got = await Promise.all(slice.map(p => readSidKind(path.join(HVSC, p))));
        // Store only the compact flags, not the header strings - this file has one
        // entry per SID and is read back by report.mjs too.
        slice.forEach((p, j) => {
            const k = got[j];
            kinds[p] = k ? { rsid: k.rsid, basic: k.basic, mus: k.mus } : null;
        });
    }
    fs.writeFileSync(kindCachePath, JSON.stringify({ key: kindKey, kinds }));
    process.stdout.write('done\n');
}

const skipCounts = {};
tasks = tasks.filter(t => {
    const why = skipReason(kinds[t.sidPath], { includeRsid: INCLUDE_RSID, includeBasic: INCLUDE_BASIC });
    if (!why) return true;
    skipCounts[why] = (skipCounts[why] || 0) + 1;
    return false;
});
const skipped = Object.entries(skipCounts);
if (skipped.length) {
    console.log(`  excluded ${skipped.reduce((n, [, v]) => n + v, 0).toLocaleString()} subtunes: ` +
        skipped.map(([k, v]) => `${v.toLocaleString()} ${k}`).join(', ') +
        `${INCLUDE_BASIC ? '' : '  (--include-basic to keep them)'}`);
}
console.log(`  ${tasks.length.toLocaleString()} subtunes to measure`);

// Resume: read whatever previous runs already finished. Keeping the results (not
// just the keys) is what lets --only re-measure a class of them.
const done = new Map();   // "md5:subtune" -> result
if (flags.redo) {
    for (const f of fs.readdirSync(OUT).filter(f => /^results-\d+\.jsonl$/.test(f))) {
        fs.rmSync(path.join(OUT, f));
    }
    console.log('  --redo: cleared the existing journal');
} else {
    let recovered = 0, torn = 0;
    for (const f of fs.readdirSync(OUT).filter(f => /^results-\d+\.jsonl$/.test(f))) {
        const text = fs.readFileSync(path.join(OUT, f), 'utf8');
        const lines = text.split('\n');
        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            if (!line.trim()) continue;
            try {
                const r = JSON.parse(line);
                const k = `${r.md5}:${r.subtune}`;
                // A recheck writes a second line for the same subtune; keep the newer.
                const prev = done.get(k);
                if (!prev || (r.t || 0) >= (prev.t || 0)) done.set(k, r);
                recovered++;
            } catch (e) {
                // Only the very last line can legitimately be half-written (the
                // process died mid-append); anything else is a real problem.
                if (i === lines.length - 1) torn++;
                else console.warn(`  warning: unparseable line ${i + 1} in ${f}`);
            }
        }
    }
    if (recovered) console.log(`  journal: ${done.size.toLocaleString()} subtunes measured` +
        `${recovered !== done.size ? ` (${recovered.toLocaleString()} lines incl. rechecks)` : ''}` +
        `${torn ? `, dropped ${torn} torn line` : ''}`);
}

if (flags.shuffle) {
    // Deterministic shuffle so a sampled trial run is reproducible, and so a
    // resumed run walks the same order.
    let seed = 0x9e3779b9;
    const rnd = () => (seed = (Math.imul(seed ^ (seed >>> 15), 0x2c1b3c6d) ^ (seed >>> 12)) >>> 0) / 4294967296;
    for (let i = tasks.length - 1; i > 0; i--) {
        const j = Math.floor(rnd() * (i + 1));
        [tasks[i], tasks[j]] = [tasks[j], tasks[i]];
    }
}

let pending;
if (ONLY) {
    const bad = ONLY.filter(c => !CLASSES.includes(c));
    if (bad.length) {
        console.error(`\nUnknown class in --only: ${bad.join(', ')}\nValid: ${CLASSES.join(', ')}\n`);
        process.exit(1);
    }
    pending = tasks.filter(t => {
        const r = done.get(`${t.md5}:${t.subtune}`);
        return r && ONLY.includes(classify(r));
    });
    // In recheck mode the HVSC-derived budget is exactly what already failed, so
    // give these a fixed window instead - --budget if set, else the ceiling.
    const forced = FORCE_BUDGET || MAX_BUDGET;
    for (const t of pending) t.forceBudget = forced;
    console.log(`  --only ${ONLY.join(',')}: re-measuring ${pending.length.toLocaleString()} at a ${forced}s budget`);
} else {
    pending = tasks.filter(t => !done.has(`${t.md5}:${t.subtune}`));
}
const queue = LIMIT ? pending.slice(0, LIMIT) : pending;
if (!queue.length) {
    console.log(ONLY ? '\nNothing in the journal matches those classes.\n'
                     : '\nNothing left to do. Run report.mjs to build the outputs.\n');
    process.exit(0);
}
console.log(`  ${queue.length.toLocaleString()} to go, ${JOBS} worker${JOBS > 1 ? 's' : ''}, engine ${ENGINE}\n`);

fs.writeFileSync(path.join(OUT, 'run-meta.json'), JSON.stringify({
    startedAt: new Date().toISOString(),
    md5: MD5, hvsc: HVSC, engine: ENGINE, jobs: JOBS,
    minLoopSeconds: MIN_LOOP, budgetMultiple: BUDGET_MULT, maxBudgetSeconds: MAX_BUDGET,
    only: ONLY, forceBudget: FORCE_BUDGET || null,
    includeRsid: INCLUDE_RSID, includeBasic: INCLUDE_BASIC, excluded: skipCounts,
    sampleRate: SAMPLE_RATE, totalSubtunes: tasks.length,
}, null, 2));

// ---------------------------------------------------------------------------
// Run

// Journals: one append-only file per worker slot, so two threads never interleave
// into the same file and a crash can only ever truncate the final line.
const journals = Array.from({ length: JOBS }, (_, i) =>
    fs.createWriteStream(path.join(OUT, `results-${i}.jsonl`), { flags: 'a' }));

let next = 0, completed = 0, errors = 0, fellBack = 0;
const started = Date.now();
const stats = { match: 0, close: 0, half: 0, double: 0, off: 0, wild: 0, noloop: 0, capped: 0 };

const workers = journals.map((journal, slot) => {
    const w = new Worker(path.join(HERE, 'scan-worker.mjs'), {
        workerData: {
            publicDir: PUBLIC, hvscDir: HVSC, engine: ENGINE, sampleRate: SAMPLE_RATE,
            minLoopSeconds: MIN_LOOP, budgetMultiple: BUDGET_MULT,
            minBudgetSeconds: 45, maxBudgetSeconds: MAX_BUDGET,
        },
    });
    w.on('message', (msg) => {
        if (msg.type === 'result') {
            const r = msg.result;
            journal.write(JSON.stringify(r) + '\n');
            completed++;
            if (r.error) errors++;
            if (r.fellBack) fellBack++;
            const cls = classify(r);
            if (stats[cls] != null) stats[cls]++;
        }
        feed(w);
    });
    w.on('error', (e) => { console.error(`\nworker ${slot} died: ${e.message}`); errors++; });
    return w;
});

function feed(w) {
    if (next >= queue.length) {
        if (completed >= queue.length) finish();
        return;
    }
    w.postMessage({ type: 'task', task: queue[next++] });
}

// ---------------------------------------------------------------------------
// Progress: ONE line, rewritten in place. Printing a line per song would mean
// 80k lines of scrollback and a measurable share of the runtime spent on stdout.
const isTTY = process.stdout.isTTY;
let lastDraw = 0;
function draw(force) {
    const now = Date.now();
    if (!force && now - lastDraw < 250) return;
    lastDraw = now;
    const elapsed = (now - started) / 1000;
    const line =
        `${completed.toLocaleString()}/${queue.length.toLocaleString()} | ${hms(elapsed)} ` +
        `| match ${stats.match} close ${stats.close} off ${stats.off} wild ${stats.wild} ` +
        `half ${stats.half + stats.double} noloop ${stats.noloop} capped ${stats.capped}` +
        (errors ? ` | err ${errors}` : '') + (fellBack ? ` | fp-rescue ${fellBack}` : '');
    if (isTTY) {
        process.stdout.write('\r' + line.slice(0, (process.stdout.columns || 200) - 1).padEnd(0));
    } else if (force || now - lastLogLine > 30000) {
        lastLogLine = now;
        console.log(line);
    }
}
let lastLogLine = 0;
const hms = (s) => {
    s = Math.round(s);
    const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = s % 60;
    return h ? `${h}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}` : `${m}:${String(sec).padStart(2, '0')}`;
};
const ticker = setInterval(() => draw(false), 250);

// A durable breadcrumb trail, so an unattended overnight run leaves evidence of
// how it was going even though the live display is a single rewritten line.
const progressLog = fs.createWriteStream(path.join(OUT, 'progress.log'), { flags: 'a' });
progressLog.write(`\n=== ${new Date().toISOString()} | ${queue.length} queued | ${JOBS} jobs | engine ${ENGINE} ===\n`);
const heartbeat = setInterval(() => {
    progressLog.write(`${new Date().toISOString()} ${completed}/${queue.length} ` +
        `match=${stats.match} close=${stats.close} off=${stats.off} wild=${stats.wild} ` +
        `noloop=${stats.noloop} capped=${stats.capped} err=${errors}\n`);
}, 300000);

let finished = false;
async function finish() {
    if (finished) return;
    finished = true;
    clearInterval(ticker); clearInterval(heartbeat);
    draw(true);
    if (isTTY) process.stdout.write('\n');
    for (const w of workers) w.postMessage({ type: 'exit' });
    await Promise.all(journals.map(j => new Promise(r => j.end(r))));
    const mins = (Date.now() - started) / 60000;
    console.log(`\nMeasured ${completed.toLocaleString()} subtunes in ${mins.toFixed(1)} min ` +
        `(${(completed / Math.max(mins * 60, 1e-6)).toFixed(1)}/s)`);
    console.log(`  match ${stats.match}  close ${stats.close}  off ${stats.off}  wild ${stats.wild}` +
        `  noloop ${stats.noloop}  capped ${stats.capped}  errors ${errors}`);
    if (fellBack) console.log(`  ${fellBack} tune(s) rendered silent on ${ENGINE} and were re-scanned on libsidplayfp`);
    progressLog.write(`${new Date().toISOString()} DONE ${completed}/${queue.length}\n`);
    progressLog.end();
    console.log(`\nJournal: ${OUT}`);
    console.log(`Next:    node ${path.relative(REPO, path.join(HERE, 'report.mjs'))}\n`);
    process.exit(0);
}

// Ctrl-C mid-run is a supported way to stop: everything already measured is in
// the journal, so the next run picks up from here.
process.on('SIGINT', () => {
    clearInterval(ticker); clearInterval(heartbeat);
    if (isTTY) process.stdout.write('\n');
    console.log(`\nStopped. ${completed.toLocaleString()} measured this session and saved.`);
    console.log('Run the same command again to carry on where you left off.\n');
    Promise.all(journals.map(j => new Promise(r => j.end(r)))).then(() => process.exit(130));
});

function parseArgs(argv) {
    const out = {};
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (!a.startsWith('--')) continue;
        const key = a.slice(2);
        const nextArg = argv[i + 1];
        if (nextArg && !nextArg.startsWith('--')) { out[key] = nextArg; i++; }
        else out[key] = true;
    }
    return out;
}
