#if !GFX_DONOR // graphics-donor builds carry no code/tables
//; =============================================================================
//;                          FREQUENCY / RELEASE TABLES
//; SID frequency-to-bar lookup (3 ranges) and ADSR release-rate tables used
//; by the spectrum analyser. FreqTable.bin is generated by FreqTableGen.py.
//; =============================================================================

.var file_freqTable = LoadBinary("FreqTable.bin")

//; Unaligned on purpose: page alignment only saved a 1-cycle crossing penalty
//; on a handful of per-frame lookups, and the padding cost ~256 bytes that
//; the WithLogo players need below their bitmap.
FreqToBarLo: .fill 256, file_freqTable.get(i + 0)
//; Only indices 0..191 are reachable (see the mid-table index math), so the
//; 64 pad entries are dropped.
FreqToBarMid: .fill 192, file_freqTable.get(i + 256)
//; The high table is only ever indexed with Y >= $40 (frequencies >= $4000),
//; so the first 64 entries are never read - store just the live 192 and
//; alias the label 64 bytes back.
FreqToBarHiData: .fill 192, file_freqTable.get(i + 512 + 64)
.label FreqToBarHi = FreqToBarHiData - $40

.const SUSTAIN_MIN = MAX_BAR_HEIGHT / 6
.const SUSTAIN_MAX = MAX_BAR_HEIGHT
sustainToHeight:
    .fill 16, SUSTAIN_MIN + (i * (SUSTAIN_MAX - SUSTAIN_MIN)) / 15.0

.const RELEASE_RATE_SCALE = 1.0
.const RELEASE_RATE_EXTRA = 64.0

.const REL_DIV0  = 1.5   * 0.7
.const REL_DIV1  = 3.0   * 0.7
.const REL_DIV2  = 6.0   * 0.7
.const REL_DIV3  = 9.4   * 0.7
.const REL_DIV4  = 13.4  * 0.7
.const REL_DIV5  = 19.0  * 0.7
.const REL_DIV6  = 26.8  * 0.7
.const REL_DIV7  = 49    * 0.7
.const REL_DIV8  = 62    * 0.7
.const REL_DIV9  = 70    * 0.7
.const REL_DIV10 = 75.0  * 0.7
.const REL_DIV11 = 80.0  * 0.7
.const REL_DIV12 = 85.4  * 0.7
.const REL_DIV13 = 90.0  * 0.7
.const REL_DIV14 = 95.0  * 0.7
.const REL_DIV15 = 100.0 * 0.7

releaseRateLo:
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV0 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV1 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV2 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV3 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV4 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV5 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV6 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV7 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV8 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV9 ) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV10) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV11) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV12) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV13) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV14) + RELEASE_RATE_EXTRA)
    .byte <((MAX_BAR_HEIGHT * 256.0 / REL_DIV15) + RELEASE_RATE_EXTRA)

releaseRateHi:
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV0 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV1 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV2 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV3 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV4 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV5 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV6 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV7 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV8 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV9 ) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV10) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV11) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV12) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV13) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV14) + RELEASE_RATE_EXTRA)
    .byte >((MAX_BAR_HEIGHT * RELEASE_RATE_SCALE * 256.0 / REL_DIV15) + RELEASE_RATE_EXTRA)
#endif // !GFX_DONOR
