#!/usr/bin/env python3
"""build-icon-font.py - subset the icon font down to the icons the site uses.

The page pulled Font Awesome's whole solid set from cdnjs: ~150 KB of webfont
plus ~100 KB of CSS, for 59 glyphs, from a third-party origin on the critical
path. This writes a subset of just those glyphs, plus the small stylesheet that
names them, so nothing is fetched cross-origin at all.

Output (generated - do not edit by hand):
    public/fonts/sidquake-icons.woff2
    public/icons.css

Needs Python with fonttools and brotli:
    pip install fonttools brotli

Run it after adding or removing an `fa-` icon in the markup:
    python3 scripts/build-icon-font.py [--check]

--check rebuilds into a temp directory and reports whether the committed files
are still current, without overwriting them.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(ROOT, 'public')
VERSION = '6.4.0'
CSS_URL = f'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/{VERSION}/css/all.min.css'
FONT_URL = f'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/{VERSION}/webfonts/fa-solid-900.woff2'
FAMILY = 'SIDquake Icons'


# Class names that style an icon rather than choosing one.
MODIFIERS = {
    'fa', 'fas', 'far', 'fab', 'fa-solid', 'fa-regular', 'fa-brands', 'fa-fw',
    'fa-spin', 'fa-pulse', 'fa-border', 'fa-li', 'fa-lg', 'fa-xs', 'fa-sm',
    'fa-2x', 'fa-3x', 'fa-4x', 'fa-5x', 'fa-stack', 'fa-inverse',
    'fa-rotate-90', 'fa-rotate-180', 'fa-rotate-270', 'fa-flip-horizontal',
    'fa-flip-vertical', 'fa-ul', 'fa-beat', 'fa-fade', 'fa-flip', 'fa-shake',
    'fa-bounce', 'fa-spin-pulse', 'fa-spin-reverse',
}


def used_icons():
    """Every fa- icon named anywhere the browser will see it."""
    names = set()
    pattern = re.compile(r'fa-[a-z0-9-]+')
    for dirpath, dirnames, filenames in os.walk(PUBLIC):
        # Skip the extracted HVSC archive and anything generated.
        dirnames[:] = [d for d in dirnames if d not in ('HVSC', 'fonts')]
        for name in filenames:
            # JSON only under prg/, where the visualizer registry names an icon
            # per card. The HVSC index is 12 MB of tune commentary and will
            # happily contain "...fa-coached..." inside an English sentence.
            if name.endswith('.json'):
                if os.path.basename(dirpath) != 'prg':
                    continue
            elif not name.endswith(('.html', '.js', '.css')):
                continue
            if name == 'icons.css':          # our own output
                continue
            path = os.path.join(dirpath, name)
            try:
                text = open(path, encoding='utf-8', errors='ignore').read()
            except OSError:
                continue
            for hit in pattern.findall(text):
                if hit not in MODIFIERS:
                    names.add(hit[3:])
    return names


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def codepoints(css_text, wanted):
    """name -> codepoint, from Font Awesome's own stylesheet.

    One codepoint often answers to several names - `.fa-cogs` and `.fa-gears`
    share a rule - so read every selector in each rule, not just the first.
    """
    table = {}
    for selectors, cp in re.findall(
            r'((?:\.fa-[a-z0-9-]+:before,)*\.fa-[a-z0-9-]+:before)\{content:"\\([0-9a-f]+)"\}',
            css_text):
        for name in re.findall(r'\.fa-([a-z0-9-]+):before', selectors):
            table[name] = cp
    found, missing = {}, []
    for name in sorted(wanted):
        if name in table:
            found[name] = int(table[name], 16)
        else:
            missing.append(name)
    return found, missing


def write_css(path, glyphs):
    rules = '\n'.join(
        f'.fa-{name}::before {{ content: "\\{cp:x}"; }}'
        for name, cp in sorted(glyphs.items()))
    open(path, 'w', encoding='utf-8').write(f"""/* icons.css - GENERATED by scripts/build-icon-font.py. Do not edit by hand.
 *
 * The {len(glyphs)} icons this site actually uses, out of Font Awesome {VERSION}'s
 * solid set. Replaces ~100 KB of stylesheet and ~150 KB of webfont fetched from
 * cdnjs with a subset served from our own origin.
 *
 * Add or remove an `fa-` class in the markup and re-run the script.
 */
@font-face {{
    font-family: "{FAMILY}";
    font-style: normal;
    font-weight: 900;
    font-display: block;
    src: url("fonts/sidquake-icons.woff2") format("woff2");
}}

.fa,
.fas,
.fa-solid {{
    font-family: "{FAMILY}";
    font-weight: 900;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    line-height: 1;
    text-rendering: auto;
}}

{rules}
""")


def build(out_dir, quiet=False):
    wanted = used_icons()
    css = fetch(CSS_URL).decode('utf-8')
    glyphs, missing = codepoints(css, wanted)
    if missing:
        print(f'warning: no glyph for {", ".join(missing)} - check the class name',
              file=sys.stderr)
    font = fetch(FONT_URL)

    os.makedirs(os.path.join(out_dir, 'fonts'), exist_ok=True)
    src = os.path.join(out_dir, 'fa-solid-900.woff2')
    open(src, 'wb').write(font)

    dest = os.path.join(out_dir, 'fonts', 'sidquake-icons.woff2')
    subprocess.run([
        sys.executable, '-m', 'fontTools.subset', src,
        '--unicodes=' + ','.join(f'U+{cp:04X}' for cp in sorted(glyphs.values())),
        '--flavor=woff2',
        '--layout-features=',
        '--no-hinting',
        '--desubroutinize',
        '--name-IDs=',
        '--output-file=' + dest,
    ], check=True, capture_output=True)
    os.remove(src)

    write_css(os.path.join(out_dir, 'icons.css'), glyphs)
    if not quiet:
        print(f'{len(glyphs)} icons: {len(font) // 1024} KB -> '
              f'{os.path.getsize(dest) // 1024} KB font, '
              f'{os.path.getsize(os.path.join(out_dir, "icons.css"))} B css')
    return glyphs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='build to a temp directory and diff against the committed files')
    args = ap.parse_args()

    if not args.check:
        build(PUBLIC)
        return

    with tempfile.TemporaryDirectory() as tmp:
        build(tmp, quiet=True)
        stale = []
        for rel in ('icons.css', os.path.join('fonts', 'sidquake-icons.woff2')):
            a, b = os.path.join(PUBLIC, rel), os.path.join(tmp, rel)
            if not os.path.exists(a) or open(a, 'rb').read() != open(b, 'rb').read():
                stale.append(rel)
        if stale:
            print('out of date: ' + ', '.join(stale))
            sys.exit(1)
        print('icon font and stylesheet are current')


if __name__ == '__main__':
    main()
