#!/usr/bin/env python3
"""Generate wasm/roms_data.h from roms/*.bin (C64 KERNAL/BASIC/CHARGEN).

The header embeds the ROM images directly in sidplayfp.wasm so the player
needs no extra network fetches or filesystem support.

Usage: python scripts/gen-roms-header.py
"""
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROMS = [
    ("kernal", ROOT / "roms" / "kernal.bin", 8192),
    ("basic", ROOT / "roms" / "basic.bin", 8192),
    ("chargen", ROOT / "roms" / "chargen.bin", 4096),
]
OUT = ROOT / "wasm" / "roms_data.h"


def main():
    lines = [
        "// roms_data.h - C64 system ROMs embedded for libsidplayfp.",
        "// GENERATED by scripts/gen-roms-header.py from roms/*.bin - do not edit.",
        "// See roms/README.md for origin and licensing.",
        "#ifndef SIDQUAKE_ROMS_DATA_H",
        "#define SIDQUAKE_ROMS_DATA_H",
        "",
        "#include <cstdint>",
        "",
    ]
    for name, path, expected_size in ROMS:
        data = path.read_bytes()
        if len(data) != expected_size:
            raise SystemExit(f"{path}: expected {expected_size} bytes, got {len(data)}")
        md5 = hashlib.md5(data).hexdigest()
        lines.append(f"// {path.name}: {len(data)} bytes, md5 {md5}")
        lines.append(f"static const uint8_t ROM_{name.upper()}[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            chunk = ",".join(f"0x{b:02X}" for b in data[i:i + 16])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
    lines.append("#endif // SIDQUAKE_ROMS_DATA_H")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
